### ISSUE TITLE
Website fault on Chrome Browser

### ISSUE THREAD

**Issue by rayBlock** [webmaeistro/gatsby-starter-banshorian#1]
Chrome Browser seems to cut your Website on the Top. Brave as well. 
![Screen Shot 2020-09-16 at 21 07 55](https://user-images.githubusercontent.com/23381827/93381302-be364d00-f860-11ea-8210-8acc517525d0.png)
![Screen Shot 2020-09-16 at 21 07 36](https://user-images.githubusercontent.com/23381827/93381303-becee380-f860-11ea-8815-79211b7d7d69.png)

Safari handles it fine. - Haven't tried other browsers

Great Website btw.

**Comment by webmaeistro** [comment]
@Raysayhey  Hi Thanks for heads up! :D 
 I did some fixes and the latest deploy now has it working fine

![image](https://user-images.githubusercontent.com/19165833/93668681-5cf3c100-fa8e-11ea-98be-2055bbc4449d.png)
![image](https://user-images.githubusercontent.com/19165833/93668717-b360ff80-fa8e-11ea-90ed-ba565d5c954a.png)
https://gatsby-starter-banshorian.vercel.app/
the fault was in a workaround where a invisible SVG line had a properties of width=auto and height=auto. :) 
Ill be closing this issue! :)
